export const tracks = [
  {
    key: "1",
    date: "11-10-2024",
    songName: "Yo No Soy Celoso",
    artist: "Bad Bunny",
    album: "Un Verano Sin Ti",
  },
  {
    key: "2",
    date: "10-10-2024",
    songName: "Sicko Mode",
    artist: "Travis Scott",
    album: "Astroworld",
  },
  {
    key: "3",
    date: "09-10-2024",
    songName: "God's Plan",
    artist: "Drake",
    album: "Scorpion",
  },
  {
    key: "4",
    date: "08-10-2024",
    songName: "HUMBLE.",
    artist: "Kendrick Lamar",
    album: "DAMN.",
  },
  {
    key: "5",
    date: "07-10-2024",
    songName: "Life Is Good",
    artist: "Future ft. Drake",
    album: "High Off Life",
  },
  {
    key: "6",
    date: "06-10-2024",
    songName: "The Box",
    artist: "Roddy Ricch",
    album: "Please Excuse Me for Being Antisocial",
  },
  {
    key: "7",
    date: "05-10-2024",
    songName: "Old Town Road",
    artist: "Lil Nas X",
    album: "7 EP",
  },
  {
    key: "8",
    date: "04-10-2024",
    songName: "No Role Modelz",
    artist: "J. Cole",
    album: "2014 Forest Hills Drive",
  },
  {
    key: "9",
    date: "03-10-2024",
    songName: "Mo Bamba",
    artist: "Sheck Wes",
    album: "Mudboy",
  },
  {
    key: "10",
    date: "02-10-2024",
    songName: "Juicy",
    artist: "The Notorious B.I.G.",
    album: "Ready to Die",
  },
  {
    key: "11",
    date: "01-10-2024",
    songName: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile Soundtrack",
  },
  {
    key: "12",
    date: "30-09-2024",
    songName: "Laugh Now Cry Later",
    artist: "Drake ft. Lil Durk",
    album: "Certified Lover Boy",
  },
  {
    key: "13",
    date: "29-09-2024",
    songName: "Money Trees",
    artist: "Kendrick Lamar ft. Jay Rock",
    album: "good kid, m.A.A.d city",
  },
  {
    key: "14",
    date: "28-09-2024",
    songName: "All of the Lights",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
  },
  {
    key: "15",
    date: "27-09-2024",
    songName: "XO Tour Llif3",
    artist: "Lil Uzi Vert",
    album: "Luv Is Rage 2",
  },
  {
    key: "16",
    date: "26-09-2024",
    songName: "Mask Off",
    artist: "Future",
    album: "FUTURE",
  },
  {
    key: "17",
    date: "25-09-2024",
    songName: "Suge",
    artist: "DaBaby",
    album: "Baby on Baby",
  },
  {
    key: "18",
    date: "24-09-2024",
    songName: "Goosebumps",
    artist: "Travis Scott",
    album: "Birds in the Trap Sing McKnight",
  },
  {
    key: "19",
    date: "23-09-2024",
    songName: "Hotline Bling",
    artist: "Drake",
    album: "Views",
  },
  {
    key: "20",
    date: "22-09-2024",
    songName: "GOD DID",
    artist: "DJ Khaled ft. Rick Ross, Lil Wayne, Jay-Z, John Legend, Fridayy",
    album: "GOD DID",
  },
  {
    key: "21",
    date: "21-09-2024",
    songName: "ROCKSTAR",
    artist: "DaBaby ft. Roddy Ricch",
    album: "Blame It on Baby",
  },
  {
    key: "22",
    date: "20-09-2024",
    songName: "Drip Too Hard",
    artist: "Lil Baby & Gunna",
    album: "Drip Harder",
  },
  {
    key: "23",
    date: "19-09-2024",
    songName: "Industry Baby",
    artist: "Lil Nas X ft. Jack Harlow",
    album: "MONTERO",
  },
  {
    key: "24",
    date: "18-09-2024",
    songName: "What's Next",
    artist: "Drake",
    album: "Scary Hours 2",
  },
  {
    key: "25",
    date: "17-09-2024",
    songName: "Franchise",
    artist: "Travis Scott ft. Young Thug, M.I.A.",
    album: "Franchise (Single)",
  },
  {
    key: "26",
    date: "16-09-2024",
    songName: "Thotiana",
    artist: "Blueface",
    album: "Famous Cryp",
  },
  {
    key: "27",
    date: "15-09-2024",
    songName: "In Da Club",
    artist: "50 Cent",
    album: "Get Rich or Die Tryin'",
  },
  {
    key: "28",
    date: "14-09-2024",
    songName: "Nonstop",
    artist: "Drake",
    album: "Scorpion",
  },
  {
    key: "29",
    date: "13-09-2024",
    songName: "The London",
    artist: "Young Thug ft. J. Cole, Travis Scott",
    album: "So Much Fun",
  },
  {
    key: "30",
    date: "12-09-2024",
    songName: "Savage",
    artist: "Megan Thee Stallion",
    album: "Suga",
  },
  {
    key: "31",
    date: "11-09-2024",
    songName: "Bodak Yellow",
    artist: "Cardi B",
    album: "Invasion of Privacy",
  },
  {
    key: "32",
    date: "10-09-2024",
    songName: "Loyalty",
    artist: "Kendrick Lamar ft. Rihanna",
    album: "DAMN.",
  },
  {
    key: "33",
    date: "09-09-2024",
    songName: "Love Sosa",
    artist: "Chief Keef",
    album: "Finally Rich",
  },
  {
    key: "34",
    date: "08-09-2024",
    songName: "Mercy",
    artist: "Kanye West ft. Big Sean, Pusha T, 2 Chainz",
    album: "Cruel Summer",
  },
  {
    key: "35",
    date: "07-09-2024",
    songName: "Panda",
    artist: "Desiigner",
    album: "New English",
  },
  {
    key: "36",
    date: "06-09-2024",
    songName: "Bank Account",
    artist: "21 Savage",
    album: "Issa Album",
  },
  {
    key: "37",
    date: "05-09-2024",
    songName: "Hot",
    artist: "Young Thug ft. Gunna",
    album: "So Much Fun",
  },
  {
    key: "38",
    date: "04-09-2024",
    songName: "Lucid Dreams",
    artist: "Juice WRLD",
    album: "Goodbye & Good Riddance",
  },
  {
    key: "39",
    date: "03-09-2024",
    songName: "Suge",
    artist: "DaBaby",
    album: "Baby on Baby",
  },
  {
    key: "40",
    date: "02-09-2024",
    songName: "WAP",
    artist: "Cardi B ft. Megan Thee Stallion",
    album: "WAP (Single)",
  },
  {
    key: "41",
    date: "01-09-2024",
    songName: "For the Night",
    artist: "Pop Smoke ft. Lil Baby, DaBaby",
    album: "Shoot for the Stars, Aim for the Moon",
  },
  {
    key: "42",
    date: "31-08-2024",
    songName: "Ransom",
    artist: "Lil Tecca",
    album: "We Love You Tecca",
  },
  {
    key: "43",
    date: "30-08-2024",
    songName: "Congratulations",
    artist: "Post Malone ft. Quavo",
    album: "Stoney",
  },
  {
    key: "44",
    date: "29-08-2024",
    songName: "Trap Queen",
    artist: "Fetty Wap",
    album: "Fetty Wap",
  },
  {
    key: "45",
    date: "28-08-2024",
    songName: "Started From the Bottom",
    artist: "Drake",
    album: "Nothing Was the Same",
  },
  {
    key: "46",
    date: "27-08-2024",
    songName: "Bop",
    artist: "DaBaby",
    album: "KIRK",
  },
  {
    key: "47",
    date: "26-08-2024",
    songName: "Butterfly Effect",
    artist: "Travis Scott",
    album: "Astroworld",
  },
  {
    key: "48",
    date: "25-08-2024",
    songName: "Broccoli",
    artist: "DRAM ft. Lil Yachty",
    album: "Big Baby DRAM",
  },
  {
    key: "49",
    date: "24-08-2024",
    songName: "Plug Walk",
    artist: "Rich The Kid",
    album: "The World Is Yours",
  },
  {
    key: "50",
    date: "23-08-2024",
    songName: "Magnolia",
    artist: "Playboi Carti",
    album: "Playboi Carti",
  },
  {
    key: "51",
    date: "22-08-2024",
    songName: "Big Bank",
    artist: "YG ft. 2 Chainz, Big Sean, Nicki Minaj",
    album: "Stay Dangerous",
  },
];
