export const tracks = [
  {
    key: "1",
    ranking: "1",
    songName: "Yo No Soy Celoso",
    artist: "Bad Bunny",
    album: "Un Verano Sin Ti",
  },
  {
    key: "2",
    ranking: "2",
    songName: "Sicko Mode",
    artist: "Travis Scott",
    album: "Astroworld",
  },
  {
    key: "3",
    ranking: "3",
    songName: "God's Plan",
    artist: "Drake",
    album: "Scorpion",
  },
  {
    key: "4",
    ranking: "4",
    songName: "HUMBLE.",
    artist: "Kendrick Lamar",
    album: "DAMN.",
  },
  {
    key: "5",
    ranking: "5",
    songName: "Life Is Good",
    artist: "Future ft. Drake",
    album: "High Off Life",
  },
  {
    key: "6",
    ranking: "6",
    songName: "The Box",
    artist: "Roddy Ricch",
    album: "Please Excuse Me for Being Antisocial",
  },
  {
    key: "7",
    ranking: "7",
    songName: "Old Town Road",
    artist: "Lil Nas X",
    album: "7 EP",
  },
  {
    key: "8",
    ranking: "8",
    songName: "No Role Modelz",
    artist: "J. Cole",
    album: "2014 Forest Hills Drive",
  },
  {
    key: "9",
    ranking: "9",
    songName: "Mo Bamba",
    artist: "Sheck Wes",
    album: "Mudboy",
  },
  {
    key: "10",
    ranking: "10",
    songName: "Juicy",
    artist: "The Notorious B.I.G.",
    album: "Ready to Die",
  },
  {
    key: "11",
    ranking: "11",
    songName: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile Soundtrack",
  },
  {
    key: "12",
    ranking: "12",
    songName: "Laugh Now Cry Later",
    artist: "Drake ft. Lil Durk",
    album: "Certified Lover Boy",
  },
  {
    key: "13",
    ranking: "13",
    songName: "Money Trees",
    artist: "Kendrick Lamar ft. Jay Rock",
    album: "good kid, m.A.A.d city",
  },
  {
    key: "14",
    ranking: "14",
    songName: "All of the Lights",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
  },
  {
    key: "15",
    ranking: "15",
    songName: "XO Tour Llif3",
    artist: "Lil Uzi Vert",
    album: "Luv Is Rage 2",
  },
  {
    key: "16",
    ranking: "16",
    songName: "Mask Off",
    artist: "Future",
    album: "FUTURE",
  },
  {
    key: "17",
    ranking: "17",
    songName: "Suge",
    artist: "DaBaby",
    album: "Baby on Baby",
  },
  {
    key: "18",
    ranking: "18",
    songName: "Goosebumps",
    artist: "Travis Scott",
    album: "Birds in the Trap Sing McKnight",
  },
  {
    key: "19",
    ranking: "19",
    songName: "Hotline Bling",
    artist: "Drake",
    album: "Views",
  },
  {
    key: "20",
    ranking: "20",
    songName: "GOD DID",
    artist: "DJ Khaled ft. Rick Ross, Lil Wayne, Jay-Z, John Legend, Fridayy",
    album: "GOD DID",
  },
  {
    key: "21",
    ranking: "21",
    songName: "ROCKSTAR",
    artist: "DaBaby ft. Roddy Ricch",
    album: "Blame It on Baby",
  },
  {
    key: "22",
    ranking: "22",
    songName: "Drip Too Hard",
    artist: "Lil Baby & Gunna",
    album: "Drip Harder",
  },
  {
    key: "23",
    ranking: "23",
    songName: "Industry Baby",
    artist: "Lil Nas X ft. Jack Harlow",
    album: "MONTERO",
  },
  {
    key: "24",
    ranking: "24",
    songName: "What's Next",
    artist: "Drake",
    album: "Scary Hours 2",
  },
  {
    key: "25",
    ranking: "25",
    songName: "Franchise",
    artist: "Travis Scott ft. Young Thug, M.I.A.",
    album: "Franchise (Single)",
  },
  {
    key: "26",
    ranking: "26",
    songName: "Thotiana",
    artist: "Blueface",
    album: "Famous Cryp",
  },
  {
    key: "27",
    ranking: "27",
    songName: "In Da Club",
    artist: "50 Cent",
    album: "Get Rich or Die Tryin'",
  },
  {
    key: "28",
    ranking: "28",
    songName: "Nonstop",
    artist: "Drake",
    album: "Scorpion",
  },
  {
    key: "29",
    ranking: "29",
    songName: "The London",
    artist: "Young Thug ft. J. Cole, Travis Scott",
    album: "So Much Fun",
  },
  {
    key: "30",
    ranking: "30",
    songName: "Savage",
    artist: "Megan Thee Stallion",
    album: "Suga",
  },
  {
    key: "31",
    ranking: "31",
    songName: "Bodak Yellow",
    artist: "Cardi B",
    album: "Invasion of Privacy",
  },
  {
    key: "32",
    ranking: "32",
    songName: "Loyalty",
    artist: "Kendrick Lamar ft. Rihanna",
    album: "DAMN.",
  },
  {
    key: "33",
    ranking: "33",
    songName: "Love Sosa",
    artist: "Chief Keef",
    album: "Finally Rich",
  },
  {
    key: "34",
    ranking: "34",
    songName: "Mercy",
    artist: "Kanye West ft. Big Sean, Pusha T, 2 Chainz",
    album: "Cruel Summer",
  },
  {
    key: "35",
    ranking: "35",
    songName: "Panda",
    artist: "Desiigner",
    album: "New English",
  },
  {
    key: "36",
    ranking: "36",
    songName: "Bank Account",
    artist: "21 Savage",
    album: "Issa Album",
  },
  {
    key: "37",
    ranking: "37",
    songName: "Hot",
    artist: "Young Thug ft. Gunna",
    album: "So Much Fun",
  },
  {
    key: "38",
    ranking: "38",
    songName: "Lucid Dreams",
    artist: "Juice WRLD",
    album: "Goodbye & Good Riddance",
  },
  {
    key: "39",
    ranking: "39",
    songName: "Suge",
    artist: "DaBaby",
    album: "Baby on Baby",
  },
  {
    key: "40",
    ranking: "40",
    songName: "WAP",
    artist: "Cardi B ft. Megan Thee Stallion",
    album: "WAP (Single)",
  },
  {
    key: "41",
    ranking: "41",
    songName: "For the Night",
    artist: "Pop Smoke ft. Lil Baby, DaBaby",
    album: "Shoot for the Stars, Aim for the Moon",
  },
  {
    key: "42",
    ranking: "42",
    songName: "Ransom",
    artist: "Lil Tecca",
    album: "We Love You Tecca",
  },
  {
    key: "43",
    ranking: "43",
    songName: "Congratulations",
    artist: "Post Malone ft. Quavo",
    album: "Stoney",
  },
  {
    key: "44",
    ranking: "44",
    songName: "Trap Queen",
    artist: "Fetty Wap",
    album: "Fetty Wap",
  },
  {
    key: "45",
    ranking: "45",
    songName: "Started From the Bottom",
    artist: "Drake",
    album: "Nothing Was the Same",
  },
  {
    key: "46",
    ranking: "46",
    songName: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
  },
  {
    key: "47",
    ranking: "47",
    songName: "Hot Girl Bummer",
    artist: "Blackbear",
    album: "Anonymous",
  },
  {
    key: "48",
    ranking: "48",
    songName: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    album: "F*CK LOVE (Savage)",
  },
  {
    key: "49",
    ranking: "49",
    songName: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    album: "Planet Her",
  },
  {
    key: "50",
    ranking: "50",
    songName: "Peaches",
    artist: "Justin Bieber ft. Daniel Caesar, Giveon",
    album: "Justice",
  },
  {
    key: "51",
    ranking: "51",
    songName: "Levitating",
    artist: "Dua Lipa ft. DaBaby",
    album: "Future Nostalgia",
  },
  {
    key: "52",
    ranking: "52",
    songName: "Happier Than Ever",
    artist: "Billie Eilish",
    album: "Happier Than Ever",
  },
  {
    key: "53",
    ranking: "53",
    songName: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
  },
  {
    key: "54",
    ranking: "54",
    songName: "Better Days",
    artist: "OneRepublic",
    album: "Human",
  },
  {
    key: "55",
    ranking: "55",
    songName: "Shivers",
    artist: "Ed Sheeran",
    album: "=",
  },
  {
    key: "56",
    ranking: "56",
    songName: "Take My Breath",
    artist: "The Weeknd",
    album: "Dawn FM",
  },
  {
    key: "57",
    ranking: "57",
    songName: "Good 4 U",
    artist: "Olivia Rodrigo",
    album: "SOUR",
  },
  {
    key: "58",
    ranking: "58",
    songName: "Montero (Call Me By Your Name)",
    artist: "Lil Nas X",
    album: "MONTERO",
  },
  {
    key: "59",
    ranking: "59",
    songName: "Need To Know",
    artist: "Doja Cat",
    album: "Planet Her",
  },
  {
    key: "60",
    ranking: "60",
    songName: "Stay With Me",
    artist: "Sam Smith",
    album: "In the Lonely Hour",
  },
];
